### ISSUE TITLE
Создать рест эндпоинт - заглушку

### ISSUE THREAD

**Issue by r331** [faasj/builder#1]
Сервис gateway будет вызывать данный эндпоинт для получения данных по билду и его старту.
Методы должны быть следующие
public String getBuildLogs(UUID build) 
public Build getBuild(UUID build) 
public BuildDto startBuild(FunctionBuildDto function) 

Продумать что передавать в дто

**Comment by i7bro** [comment]
image, code, envVar... А это не тот же FunctionDto из gateway?

**Comment by r331** [comment]
Практически. Но, например, данные по ресурсам туда передавать не надо

**Comment by i7bro** [comment]
Не понятно что будет в сущности Build хранится. По сути, билд это же просто Image в докере
